version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14  # Replace with your desired Node.js version
    commands:
      - npm install
  build:
    commands:
      - npm run build

artifacts:
  files:
    - "**/*"
  base-directory: build